### ISSUE TITLE
Autoprefixer 9.4.0 released

### ISSUE THREAD

**Issue by Dan503** [autoprefixer/autoprefixer.github.io#36]
Hi, can you please update to 9.4.0?

https://github.com/postcss/autoprefixer/releases/tag/9.4.0

In order to enable CSS Grid autoplacement translations, the `grid` setting will need to be set to `"autoplace"`, _not_ `true`.

**Comment by ymatuhin** [comment]
Sure, I'll do it a few hours later, thanks for the reminder

**Comment by ymatuhin** [comment]
Done, thanks again 👍

**Comment by Dan503** [comment]
You have upgraded to 9.4 but you haven't set the `grid` setting to `"autoplace"`. This means that the Autoplacement algorithm is currently disabled.

If I write this:

```css
.example {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    grid-template-rows: auto;
    grid-gap: 30px;
}
```

It should translate to this:

```css
.example {
    display: -ms-grid;
    display: grid;
    -ms-grid-columns: 1fr 30px 1fr 30px 1fr;
    grid-template-columns: 1fr 1fr 1fr;
    -ms-grid-rows: auto;
    grid-template-rows: auto;
    grid-gap: 30px;
}
.example > *:nth-child(1) {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
}
.example > *:nth-child(2) {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
}
.example > *:nth-child(3) {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
}
```
