### ISSUE TITLE
text-stroke does not get prefixed accordingly

### ISSUE THREAD

**Issue by aviallon** [autoprefixer/autoprefixer.github.io#56]
Hello, it seems that autoprefixer "forgets" to prefix `text-stroke` with `-webkit-` as mentionned in caniuse, whereas litteraly 0% of web-browsers support this property without this prefix.
For instance, with the online prefixer,
```css
.test {
    text-fill: 4px #33FF00;
}
```
gets transformed to...
```css
/* prefixed by https://autoprefixer.github.io (PostCSS: v7.0.26, autoprefixer: v9.7.3) */

.test {
    text-fill: 4px #33FF00;
}
```
I also made sure to target `last 99 version` just to be sure.
If I did something wrong, please let me know !
Have a nice day !
